name: Build & Push to Branch

on:
  push:
    branches: [ master ] # Adjust branches as needed
  pull_request:
    branches: [ master ] # Adjust branches as needed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write  # write to pages branch
  pages: write     # Github Pages
  id-token: write

jobs:
  build:
    # needs: check
    strategy:
      matrix:
        node: [ 22 ]
    runs-on: ubuntu-latest
    name: Build & Push to Branch
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm astro build

      - name: Push to pages branch
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: pages
          force_orphan: true
